version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ./mlruns:/mlruns

  mlflow:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install mlflow && 
             mlflow server --host 0.0.0.0 --port 5000 
             --backend-store-uri sqlite:///mlruns/mlflow.db 
             --default-artifact-root ./mlruns"
    volumes:
      - ./mlruns:/mlruns